spring:

  datasource:
    url: jdbc:mysql://db-cheapat9-instance-identifier.cmlb6weeeogc.ap-northeast-2.rds.amazonaws.com:3306/db_cheapat9?serverTimezone=UTC
    username: powerSell
    password: powerSell2023!
    driver-class-name: com.mysql.cj.jdbc.Driver
#cloud:
  #aws:
 #   region:
  #    static: ap-northeast-2
   #   auto: false
    #stack:
     # auto: false
  jpa:
    hibernate:
      #ddl-auto: none
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
          #show_sql: true
        #    format_sql: true
      #hbm2ddl:
      #  auto: create

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace #스프링 부트 2.x, hibernate5
  org.hibernate.orm.jdbc.bind: trace #스프링 부트 3.x,

admin:
  id: woiwufvhn
  password: eazwrdctfvy